# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Metadata-DB-File
version:      1.04
version_from: lib/Metadata/DB/File.pm
installdirs:  site
requires:
    LEOCHARRE::Class:              0
    LEOCHARRE::Database:           1.12
    LEOCHARRE::DEBUG:              0
    Metadata::DB:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
